### ISSUE TITLE
Can the local planner avoid dynamic obstacles?

### ISSUE THREAD

**Issue by jorgemiar** [noeperez/indires_navigation#9]
Hola @noeperez!

Have you been able to test this with dynamic obstacles?

**Comment by noeperez** [comment]
Hi!

No, I did not test it.
The system was not designed to handle dynamic obstacles. However, the local
planner includes the option of a subscription to a laser range finder or
different sonar ranges to perform collision avoidance with dynamic
obstacles.
Although, the performance of that part was not tested since only static
scenarios, like tunnels and caves, were considered in the project.

Best,
Noé

**Comment by jorgemiar** [comment]
Ok thank you! I might give it a try!
